export enum GlobalError {
    ERROR_VALIDATION = 'ERROR_VALIDATION',
    SESSION_INVALID = 'SESSION_INVALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    NOT_PERMITED_ACCESS = 'NOT_PERMITED_ACCESS',
    NOT_FOUND_DATA = 'NOT_FOUND_DATA',
    DATA_ALREADY_EXIST = 'DATA_ALREADY_EXIST',
    DATA_IN_USE = 'DATA_IN_USE',
}